---
apiVersion: v1
kind: Secret
metadata:
  name: daring-elbakyan-f2610c0673-bst-token
  namespace: apps-release
  labels:
    app: daring-elbakyan-f2610c0673
    managed-by: backstract
  annotations:
    backstract.io/token-scope: "storage.*,cache.*"
type: Opaque
stringData:
  token: "bst_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiYWNrc3RyYWN0LXBsYXRmb3JtIiwic3ViIjoiY29sbF9mNzk5MDk3MzlhYTA0ODZjYjgwM2QxNDgyMDI5NGQ1OCIsImF1ZCI6ImJhY2tzdHJhY3QtcmVzb3VyY2VzIiwiZW52IjoicmVsZWFzZSIsImlhdCI6MTc4OTA0MDg0NywiZXhwIjoxNzk2ODE2ODQ3LCJzY29wZXMiOlsic3RvcmFnZS4qIiwiY2FjaGUuKiJdLCJ0b2tlbl90eXBlIjoiYnN0Iiwib3duZXJfaWQiOiI5OTEyMzBkYWE1ODk0ODlmODQ2N2VhMWE1NWJlMTFlYiJ9.oKmD0iFdNzFHB-JVnOrFqABDS_vdBFzb92aUZRxA-4o"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daring-elbakyan-f2610c0673-depl
  namespace: apps-release
  labels:
    app: daring-elbakyan-f2610c0673
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daring-elbakyan-f2610c0673
      release: prometheus
  template:
    metadata:
      labels:
        app: daring-elbakyan-f2610c0673
        release: prometheus
    spec:
      #runtimeClassName: gvisor
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-configmap-daring-elbakyan-f2610c0673
            items:
              - key: alloy.river
                path: config.alloy
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
      containers:
        - name: daring-elbakyan-f2610c0673
          image: asia-south2-docker.pkg.dev/platform-test-487912/backstract-apps/backstract_apps:067ade3a1de302f9acbfc4c4abbe606bd53c8bc3
          imagePullPolicy: Always
          env:
            - name: BACKSTRACT_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: daring-elbakyan-f2610c0673-bst-token
                  key: token
            - name: BACKSTRACT_PLATFORM_URL
              value: "https://api-release.beemerbenzbentley.site/sigma"
          envFrom:
            - configMapRef:
                name: env-configmap-coll-f79909739aa0486cb803d14820294d58-deployment-ded6f7eb-6010-413a-97c6-2a8dc07c79b6
            - secretRef:
                name: app-secrets-coll-f79909739aa0486cb803d14820294d58
            - secretRef:
                name: app-resources-secrets-coll-f79909739aa0486cb803d14820294d58
                optional: true
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              memory: "250Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "1"
        - name: alloy-sidecar
          image: grafana/alloy:latest
          args:
            - "run"
            - "/etc/alloy/config.alloy"
            - "--server.http.listen-addr=0.0.0.0:12345"
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
            - name: alloy-http
              containerPort: 12345
              protocol: TCP
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: true
          resources:
            requests:
              memory: "50Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "100m"
